version: '3.5'
services:
  asf:
    image: justarchi/archisteamfarm
    container_name: asf
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - asf_data/config:/app/config
      - asf_data/plugins:/app/plugins
    ports:
      - ${PORT}:1242
    restart: unless-stopped

volumes:
  asf_data:
    driver_opts:
      type: none
      device: ${VOLUME_PATH}
      o: bind
