services:
  asf:
    image: justarchi/archisteamfarm
    container_name: asf
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${CONFIG_PATH}:/app/config
      - ${PLUGINS_PATH}:/app/plugins
    ports:
      - ${PORT}:1242
    restart: unless-stopped
