services:
  sing-box:
    image: ghcr.io/sagernet/sing-box
    container_name: sing-box
    restart: always
    volumes:
      - /srv/sing-box:/etc/sing-box
    command: -D /var/lib/sing-box -C /etc/sing-box/ run
    network_mode: host
