services:
  headscale:
    image: docker.io/headscale/headscale:v0.26
    restart: unless-stopped
    container_name: headscale
    volumes:
      - /srv/headscale/config:/etc/headscale
      - /srv/headscale/lib:/var/lib/headscale
      - /srv/headscale/run:/var/run/headscale
    command: serve
    network_mode: host

  headscale_ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    restart: unless-stopped
    container_name: headscale-ui
    ports:
      - "127.0.0.1:8081:8080"
