version: '3.5'
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - calibre:/config
      - books:/books
    ports:
      - 8081:8080
      - 8082:8081
    restart: unless-stopped
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - calibre-web:/config
      - books:/books
    ports:
      - 8083:8083
    restart: unless-stopped

volumes:
  calibre:
  calibre-web:
  books:
