services:
  couchdb:
    image: couchdb
    container_name: obsidian-livesync
    environment:
      - COUCHDB_USER=${OL_USER}
      - COUCHDB_PASSWORD=${OL_PASSWORD}
    volumes:
      - '${OL_DATA}:/opt/couchdb/data'
      - '${OL_LOCAL_INI}:/opt/couchdb/etc/local.ini'
    ports:
      - 5984:5984
    restart: unless-stopped
