services:
  openlist:
    image: 'openlistteam/openlist:latest'
    container_name: openlist
    user: '${OPENLIST_PUID}:${OPENLIST_PGID}'
    volumes:
      - '${OPENLIST_DATA}:/opt/openlist/data'
    ports:
      - '5244:5244'
    environment:
      - UMASK=022
    restart: unless-stopped
